import type { defineSub } from '@components/showcase-utils'

export const marks: Record<string, (typeof defineSub)[number][]> = {
  Chasca: ['ATK', 'CRIT'],
  Xilonen: ['DEF', 'ER'],
  Mualani: ['HP', 'CRIT'],
  Kinich: ['ATK', 'CRIT'],
  Emilie: ['ATK', 'CRIT', 'ER'],
  Clorinde: ['ATK', 'CRIT'],
  Arlecchino: ['ATK', 'CRIT'],
  Sigewinne: ['HP'],
  Chiori: ['DEF', 'CRIT'],
  Xianyun: ['ATK', 'ER'],
  Navia: ['ATK', 'CRIT'],
  Furina: ['HP', 'CRIT', 'ER'],
  Neuvillette: ['HP', 'CRIT', 'ER'],
  Wriothesley: ['ATK', 'CRIT'],
  Lyney: ['ATK', 'CRIT'],
  Baizhu: ['HP', 'ER'],
  Dehya: ['HP'],
  Alhaitham: ['EM', 'CRIT'],
  Wanderer: ['ATK', 'CRIT'],
  Nahida: ['EM', 'CRIT'],
  Cyno: ['ATK', 'EM', 'CRIT', 'ER'],
  Nilou: ['HP'],
  Tighnari: ['EM', 'CRIT'],
  'Kamisato Ayato': ['ATK', 'CRIT', 'ER'],
  Shenhe: ['ATK', 'ER'],
  Yelan: ['HP', 'CRIT', 'ER'],
  'Yae Miko': ['ATK', 'CRIT'],
  'Arataki Itto': ['DEF', 'CRIT', 'ER'],
  'Sangonomiya Kokomi': ['HP', 'ER'],
  'Raiden Shogun': ['ATK', 'CRIT', 'ER'],
  Eula: ['ATK', 'CRIT', 'ER'],
  Yoimiya: ['ATK', 'CRIT'],
  'Kaedehara Kazuha': ['EM', 'ER'],
  'Hu Tao': ['HP', 'EM', 'CRIT'],
  Keqing: ['ATK', 'CRIT'],
  Mona: ['ATK', 'CRIT', 'ER'],
  Albedo: ['DEF', 'CRIT'],
  Ganyu: ['ATK', 'CRIT', 'ER'],
  Qiqi: ['ATK', 'ER'],
  Tartaglia: ['ATK', 'CRIT'],
  Zhongli: ['HP', 'ER'],
  Klee: ['ATK', 'CRIT'],
  Xiao: ['ATK', 'CRIT', 'ER'],
  Venti: ['EM', 'ER'],
  Diluc: ['ATK', 'CRIT'],
  Jean: ['ATK', 'ER'],
  'Kamisato Ayaka': ['ATK', 'CRIT', 'ER'],

  Ororon: ['ATK', 'CRIT', 'ER'],
  Kachina: ['DEF'],
  Sethos: ['EM', 'CRIT', 'ER'],
  Gaming: ['ATK', 'CRIT', 'ER'],
  Chevreuse: ['HP', 'ER'],
  Charlotte: ['ATK', 'ER'],
  Freminet: ['ATK', 'CRIT', 'ER'],
  Lynette: ['ATK', 'CRIT', 'ER'],
  Kaveh: ['EM', 'ER'],
  Mika: ['HP', 'ER'],
  Yaoyao: ['HP', 'ER'],
  Faruzan: ['ATK', 'CRIT', 'ER'],
  Layla: ['HP'],
  Candace: ['HP', 'ER'],
  Dori: ['HP', 'ER'],
  Collei: ['ATK', 'CRIT', 'ER'],
  'Kuki Shinobu': ['HP', 'EM'],
  'Yun Jin': ['DEF', 'ER'],
  Kirara: ['HP'],
  'Shikanoin Heizou': ['ATK', 'CRIT'],
  'Kujou Sara': ['ATK', 'CRIT', 'ER'],
  Gorou: ['ER'],
  Sayu: ['ATK', 'EM', 'ER'],
  Thoma: ['HP', 'ER'],
  Yanfei: ['ATK', 'CRIT', 'ER'],
  Rosaria: ['ATK', 'CRIT', 'ER'],
  Sucrose: ['EM', 'ER'],
  Diona: ['HP', 'ER'],
  Chongyun: ['ATK', 'CRIT'],
  Noelle: ['DEF', 'CRIT', 'ER'],
  Bennett: ['HP', 'ER'],
  Fischl: ['ATK', 'CRIT'],
  Ningguang: ['ATK', 'CRIT'],
  Xingqiu: ['ATK', 'CRIT', 'ER'],
  Beidou: ['ATK', 'CRIT', 'ER'],
  Xiangling: ['ATK', 'CRIT', 'ER'],
  Amber: ['ATK', 'CRIT'],
  Razor: ['ATK', 'CRIT', 'ER'],
  Kaeya: ['ATK', 'CRIT', 'ER'],
  Barbara: ['HP', 'ER'],
  Lisa: ['ATK', 'CRIT', 'ER'],
  Aloy: ['ATK', 'CRIT'],
  default: ['CRIT'],
}
