export const data = [
  {
    id: 'fukafukafuka29',
    right_field: [
      'Shenhe',
      'Arataki Itto',
      'Sangonomiya Kokomi',
      'Raiden Shogun',
      'Kamisato Ayaka',
      'Hu Tao',
      'Xiao',
      'Tartaglia',
      'Layla',
      'Collei',
      'Shikanoin Heizou',
      'Yun Jin',
      'Gorou',
      'Thoma',
      'Kujou Sara',
      'Yanfei',
      'Xinyan',
      'Chongyun',
      'Noelle',
      'Xingqiu',
      'Barbara',
      'Kaeya',
      'Aloy',
      'Lumine',
      'Paimon',
      'Dainsleif',
    ],
  },
]
